# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# title      Travis CI Build Configuration                 +
# project    nord-tilix                                    +
# repository https://github.com/arcticicestudio/nord-tilix +
# author     Arctic Ice Studio                             +
# email      development@arcticicestudio.com               +
# copyright  Copyright (C) 2017                            +
# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#
# [References]
# Travis CI Documentation
#   (https://docs.travis-ci.com/user/languages/javascript-with-nodejs)
language: node_js
node_js:
  - "6"
  - "4"
cache: yarn
before_script:
  - yarn global add gulp
  - yarn install
script: gulp --harmony lint
